name: terraform

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/terraform.yaml
      - '**/*.tf'
      - '**/.terraform.*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        state:
          - helloworld
          - delete-databases
    defaults:
      run:
        working-directory: ${{ matrix.state }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - run: terraform fmt -check
    - run: terraform init -backend=false
    - run: terraform validate
