name: terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  helloworld:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: helloworld
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - run: terraform fmt -check
    - run: terraform validate
